version: "3.8"

services:
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment: 
      - POSTGRES_DB=fast-food-restaurant
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=root
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment: 
      PGADMIN_DEFAULT_EMAIL: admin@admin.com 
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
     - "5050:80"

  django-backend:
    container_name: django-backend
    build: ./django
    ports:
      - "8000:8000"
    volumes:
      - ./django:/app
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    depends_on:
      - postgres
  
  redis:
    container_name: redis
    image: redis:latest
    restart: always
    volumes:
      - ./id-generator/config/redis.conf:/redis.conf
    command: ["redis-server", "/redis.conf"]

  id-generator:
    container_name: id-generator
    build: ./id-generator
    ports: 
      - "8008:8008"
    volumes:
      - ./id-generator:/app
    command: ["python", "main.py"]
    depends_on:
      - redis



networks:
  default:
    external:
      name: fast-food-application

volumes: 
  pgdata: