version: "3.8"

services:
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment: 
      POSTGRES_DB: ${PG_DB}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment: 
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
     - "5050:80"

  django-backend:
    container_name: django-backend
    build: ./django
    ports:
      - "8000:8000"
    volumes:
      - ./django:/app
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    depends_on:
      - postgres
  
  redis:
    container_name: redis
    image: redis:latest
    restart: always
    volumes:
      - ./id-generator/config/redis.conf:/redis.conf
    command: ["redis-server", "/redis.conf"]

  id-generator:
    container_name: id-generator
    build: ./id-generator
    ports: 
      - "8008:8008"
    volumes:
      - ./id-generator:/app
    command: ["python", "main.py"]
    depends_on:
      - redis
  
  frontend-react:
    container_name: frontend-react
    build: ./react
    ports:
      - "3000:3000"
    volumes:
      - ./react/node_modules
      - ./react:/app
    command: ["npm", "start"]

  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - mongodata:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MG_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MG_PASSWORD}
    depends_on:
      - django-backend
    
  mongo-express:
    container_name: mongo-express
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: ${MG_EXPRESS_SERVER}
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MG_EXPRESS_ADMIN_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MG_EXPRESS_ADMIN_PASSWORD}
      ME_CONFIG_MONGODB_ENABLE_ADMIN: 'true'
    depends_on:
      - mongo

  tracking:
    container_name: tracking
    build: ./tracking
    ports:
      - "3001:3001"
    volumes:
      - ./tracking:/app
    command: ["npm", "start"]
    depends_on:
      - mongo
  
  order-delivery-time-handler:
    container_name: order-delivery-time-handler
    build: ./order-delivery-time-handler
    volumes:
      - ./order-delivery-time-handler:/app
    command: ["python", "main.py"]
    depends_on:
      - django-backend

networks:
  default:
    external:
      name: fast-food-application

volumes: 
  pgdata:
  mongodata: