version: 2.1

jobs:
  install-dependencies:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run:
          name: Create Python Dependencies
          command: make create-env
      - run:
          name: Install Dependencies
          command: |
            . venv/bin/activate
            make install
      - persist_to_workspace:
          root: ./
          paths:
            - ./
  django-test:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - attach_workspace:
          at: ./
      - run:
          name: Unittest Django
          command: |
            . venv/bin/activate
            make unittest
      - persist_to_workspace:
          root: ./
          paths:
            - ./
  docker-compose-test:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - attach_workspace:
          at: ./
      - run:
          name: Run docker compose
          command: make run-docker-compose
      - run:
          name: Test samples
          command: |
            . venv/bin/activate
            make test-run-samples
      - run:
          name: Stop docker compose
          command: make stop-docker-compose

workflows:
  sample:
    jobs:
      - install-dependencies
      - django-test:
          requires:
            - install-dependencies
      - docker-compose-test:
          requires:
            - django-test