version: "3.8"

services:
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment: 
      - POSTGRES_DB=fast-food-restaurant
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=root

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always

    environment: 
      PGADMIN_DEFAULT_EMAIL: admin@admin.com 
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
     - "5050:80"