name: CI-CD

on: [push, pull_request]

jobs:
  order-delivery-time-handler-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repo
        uses: actions/checkout@v2

      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Test machine learning api
        env:
          ML_API_URL: ${{ secrets.ML_API_URL }}
          DB_FILE: ${{ secrets.ML_DB_FILE }}
          DB_TABLE: ${{ secrets.ML_DB_TABLE }}
          DB_NAME: ${{ secrets.ML_DB_NAME }}
          DB_HOST: ${{ secrets.ML_DB_HOST }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}
        run: make order-delivery-time-handler

  api-server-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repo
        uses: actions/checkout@v2

      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Test deployment
        run: make deployment

  django-test:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repo
        uses: actions/checkout@v2

      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install Dependencies
        env:
          DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
        run: make set-up-backend

      - name: Unittest Django
        env:
          DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
          REDIS_PORT: ${{ secrets.REDIS_PORT }}
          REDIS_HOST: ${{ secrets.REDIS_HOST }}
          REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
        run: make backend-server

  tracking-server-test:
    runs-on: ubuntu-latest
    needs: [django-test, api-server-test, order-delivery-time-handler-test]
    steps:
      - name: Checkout source repo
        uses: actions/checkout@v2

      - name: Set up Node.js 16.x
        uses: actions/setup-node@v2.5.1
        with:
          node-version: "16"

      - name: Test Tracking server
        env:
          LOG_DIR: ${{ secrets.LOG_DIR }}
        run: make tracking

  id-generator-test:
    runs-on: ubuntu-latest
    needs: tracking-server-test
    steps:
      - name: Checkout source repo
        uses: actions/checkout@v2

      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: make set-up-id-generator

      - name: Test id generator
        env:
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          SERVER_PORT: ${{ secrets.SERVER_PORT }}
          REDIS_PORT: ${{ secrets.REDIS_PORT }}
          REDIS_HOST: ${{ secrets.REDIS_HOST }}
          REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
        run: make test-id-generator

  api-server-deployment:
    runs-on: ubuntu-latest
    needs: id-generator-test
    steps:
      - name: Checkout source repo
        uses: actions/checkout@v2

      - name: Deploy api-server in heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          appdir: "machine-learning-api"

      - name: Slack notify
        if: always()
        uses: rtCamp/action-slack-notify@v2.2.0
        env:
          SLACK_CHANNEL: dev
          SLACK_MESSAGE: "fast-food CI - ${{job.status}}"
          SLACK_USERNAME: Github Alert
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
