name: CI-CD

on: [push, pull_request]

jobs:
  build-and-install-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repo
        uses: actions/checkout@v2

      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Cache python dependencies
        uses: actions/cache@v2
        id: cache
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: make install

  machine-learning-api-test:
    runs-on: ubuntu-latest
    needs: build-and-install-dependencies
    steps:
      - name: Checkout source repo
        uses: actions/checkout@v2

      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Test machine learning api
        env:
          ML_API_URL: ${{ secrets.ML_API_URL }}
        run: make machine-learning-api

  api-server-test:
    runs-on: ubuntu-latest
    needs: build-and-install-dependencies
    steps:
      - name: Checkout source repo
        uses: actions/checkout@v2

      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Test deployment
        run: make deployment

  kafka-django-test:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    needs: build-and-install-dependencies
    steps:
      - name: Checkout source repo
        uses: actions/checkout@v2

      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Dependencies
        run: make install

      - name: Run docker compose
        run: make run-docker-compose

      # - name: Test samples
      #   run: make test-run-samples

      # - name: Unittest Django
      #   env:
      #     DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
      #   run: make backend-server

      - name: Stop docker compose
        if: always()
        run: make stop-docker-compose

  tracking-server-test:
    runs-on: ubuntu-latest
    needs: [kafka-django-test, api-server-test, machine-learning-api-test]
    steps:
      - name: Checkout source repo
        uses: actions/checkout@v2

      - name: Set up Node.js 16.x
        uses: actions/setup-node@v2.5.1
        with:
          node-version: "16"

      - name: Test Tracking server
        run: make tracking

  api-server-deployment:
    runs-on: ubuntu-latest
    needs: tracking-server-test
    steps:
      - name: Checkout source repo
        uses: actions/checkout@v2

      - name: Deploy api-server in heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          appdir: "data-handling"

      - name: Slack notify
        if: always()
        uses: rtCamp/action-slack-notify@v2.2.0
        env:
          SLACK_CHANNEL: dev
          SLACK_MESSAGE: "fast-food CI - ${{job.status}}"
          SLACK_USERNAME: Github Alert
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
