name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      
      - name: Install dependency
        run: |
          make install

      - name: Unittest Django
        run: |
          make unittest
      
      - name: Run docker compose
        run: |
          make run-docker-compose
      
      - name: Test samples
        run: |
          make test-run-samples
      
      - name: Stop docker compose
        run: |
          make stop-docker-compose

      - name: Slack notify
        if: always()
        uses: rtCamp/action-slack-notify@v2.2.0
        env:
          SLACK_CHANNEL: dev
          SLACK_MESSAGE: 'fast-food CI - ${{job.status}}'
          SLACK_USERNAME: Github Alert
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
