name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      
      - name: Install dependency
        run: |
          make install
      
      - name: Run docker compose
        run: |
          make run-docker-compose
      
      - name: Test samples
        run: |
          make test-run-samples
      
      - name: Stop docker compose
        run: |
          make stop-docker-compose
